# Number of days of inactivity before an issue becomes stale
daysUntilStale: 120
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  any activity in the last 120 days. If no more activity is detected,
  it will be labeled as stale and closed automatically within a week.
  
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue is stale and is being closed. 
  
  Please reopen it if there is anything to add at a later stage, 
  but make sure there isn't any newer issue open on the same topic.
